### ISSUE TITLE
Replace language with Python on `Enter`

### ISSUE THREAD

**Issue by elewing** [elewing/abstract-coding#2]
References: 

- https://github.com/blog/2231-building-your-first-atom-plugin
- https://discuss.atom.io/t/can-you-set-multiple-grammar-autocomplete-rules-for-a-filetype/30434/4

**Comment by StephanieXie** [comment]
https://github.com/Glavin001/atom-beautify
http://atom-packages.directory/category/tools-autocomplete/
https://discuss.atom.io/t/html-markdown-converter/23918

**Comment by elewing** [comment]
Useful information on creating a package [here](https://www.sitepoint.com/write-atom-packages-using-vanilla-javascript/).

**Comment by elewing** [comment]
Will have to adjust and fix keymaps for replacement; opening a new issue [here](https://github.com/elewing/abstract-coding/issues/4).
